[tool.poetry]
name = "food-crawling"
version = "0.1.0"
description = ""
authors = ["rover0811 <rover0811@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "3.9.3"
aiosignal = "1.3.1"
annotated-types = "0.7.0"
anyio = "4.6.0"
async-timeout = "4.0.3"
attrs = "23.2.0"
beautifulsoup4 = "4.4.1"
build = "1.2.2"
cachecontrol = "0.14.0"
certifi = "2024.2.2"
charset-normalizer = "3.3.2"
cleo = "2.1.0"
colorama = "0.4.6"
crashtest = "0.4.1"
distlib = "0.3.8"
distro = "1.9.0"
dulwich = "0.21.7"
exceptiongroup = "1.2.0"
fastjsonschema = "2.20.0"
filelock = "3.16.1"
frozenlist = "1.4.1"
h11 = "0.14.0"
httpcore = "1.0.5"
httpx = "0.27.2"
idna = "3.6"
importlib-metadata = "8.5.0"
iniconfig = "2.0.0"
installer = "0.7.0"
jaraco-classes = "3.4.0"
jiter = "0.5.0"
keyring = "24.3.1"
more-itertools = "10.5.0"
msgpack = "1.1.0"
multidict = "6.0.5"
numpy = "1.26.4"
openai = "1.47.0"
packaging = "24.0"
pandas = "2.0.1"
pexpect = "4.9.0"
pkginfo = "1.11.1"
platformdirs = "4.3.6"
pluggy = "1.4.0"
poetry = "1.8.3"
poetry-core = "1.9.0"
poetry-plugin-export = "1.8.0"
ptyprocess = "0.7.0"
pydantic = "2.9.2"
pydantic-core = "2.23.4"
pyproject-hooks = "1.1.0"
pytest = "8.1.1"
python-dateutil = "2.9.0.post0"
pytz = "2024.1"
pywin32-ctypes = "0.2.3"
rapidfuzz = "3.9.7"
requests = "2.29.0"
requests-toolbelt = "1.0.0"
shellingham = "1.5.4"
six = "1.16.0"
sniffio = "1.3.1"
tenacity = "8.2.3"
tomli = "2.0.1"
tomlkit = "0.13.2"
tqdm = "4.66.2"
trove-classifiers = "2024.9.12"
typing-extensions = "4.12.2"
tzdata = "2024.1"
urllib3 = "1.26.18"
virtualenv = "20.26.5"
yarl = "1.9.4"
zipp = "3.20.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
