version = 0.1

[default]
[default.global.parameters]
stack_name = "food-scrapper-default"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "ap-northeast-2"

# Development environment
[dev]
[dev.global.parameters]
stack_name = "food-scrapper-dev"

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "ap-northeast-2"

# Production environment
[prod]
[prod.global.parameters]
stack_name = "food-scrapper-prod"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "ap-northeast-2"