name: "Simple Input Workflow"
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to display"
        required: true
        default: "Hello World"
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: "Print the input"
        run: echo ${{ github.event.inputs.message }}
