name: 간단한 입력 워크플로우

on:
  workflow_dispatch:
    inputs:
      message:
        description: '출력할 메시지'
        required: true
        default: '안녕하세요'

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: 입력된 메시지 출력
        run: echo "입력한 메시지: ${{ github.event.inputs.message }}"
